pub mod apply_changes;
pub mod array_functions;
pub mod batch;
pub mod calibrate;
pub mod column;
pub mod compute;
pub mod context;
pub mod correlated;
pub mod decorrelate;
pub mod derived_columns;
pub mod epoch_decode;
pub mod executor;
pub mod expectation_results;
pub mod expr;
pub mod format;
pub mod lake_stats;
pub mod media_runtime;
pub mod nested_codec;
pub mod operator;
pub mod parallel_pool;
pub mod probe;
pub mod replication;
pub mod resilience_exec;
pub mod sequence;
pub mod shadow_write;
pub mod spill;
pub mod subquery;
pub mod table_convert;
pub mod tier_move;
pub mod trigger;
pub mod types_bridge;
pub mod variant_shred;

pub use batch::evaluate_row_filter;
pub use context::{ExecutionContext, QueryMemoryBudget};
pub use executor::{execute, execute_analyze};
pub use operator::OperatorMetrics;
