//! Temporal table support: system-versioned, application-time, and bi-temporal.
//!
//! System-versioned tables automatically track valid_from/valid_to with
//! engine-managed timestamps. Application-time tables use user-managed
//! periods. Bi-temporal tables combine both dimensions.

use zyron_common::error::{Result, ZyronError};

/// Maximum timestamp sentinel (9999-12-31 23:59:59 UTC in microseconds).
pub const MAX_TIMESTAMP: i64 = 253_402_300_799_000_000;

// ---------------------------------------------------------------------------
// Temporal table types
// ---------------------------------------------------------------------------

/// Classification of temporal table behavior.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TemporalType {
    /// System-managed transaction time (engine sets sys_start/sys_end).
    SystemVersioned,
    /// User-managed valid time (application controls period boundaries).
    ApplicationTime,
    /// Both system and application time dimensions.
    BiTemporal,
}

/// Configuration for temporal behavior on a table.
#[derive(Debug, Clone)]
pub struct TemporalConfig {
    pub temporal_type: TemporalType,
    /// System-time start column name (default: "sys_start").
    pub sys_start_column: String,
    /// System-time end column name (default: "sys_end").
    pub sys_end_column: String,
    /// Application-time period name.
    pub app_period_name: Option<String>,
    /// Application-time start column name.
    pub app_start_column: Option<String>,
    /// Application-time end column name.
    pub app_end_column: Option<String>,
}

impl Default for TemporalConfig {
    fn default() -> Self {
        Self {
            temporal_type: TemporalType::SystemVersioned,
            sys_start_column: "sys_start".to_string(),
            sys_end_column: "sys_end".to_string(),
            app_period_name: None,
            app_start_column: None,
            app_end_column: None,
        }
    }
}

// ---------------------------------------------------------------------------
// System-versioned table
// ---------------------------------------------------------------------------

/// System-versioned table with engine-managed transaction time.
///
/// On INSERT: sys_start = now, sys_end = MAX_TIMESTAMP.
/// On UPDATE: old row gets sys_end = now, new row gets sys_start = now.
/// On DELETE: row gets sys_end = now (soft delete for history).
pub struct SystemVersionedTable {
    pub table_id: u32,
    pub period_start_column: String,
    pub period_end_column: String,
}

/// Actions generated by system versioning for UPDATE operations.
#[derive(Debug, Clone)]
pub struct SystemVersionedUpdateActions {
    /// Set sys_end on the old row.
    pub old_sys_end: i64,
    /// Set sys_start on the new row.
    pub new_sys_start: i64,
    /// Set sys_end on the new row.
    pub new_sys_end: i64,
}

impl SystemVersionedTable {
    /// Creates a new system-versioned table configuration.
    pub fn new(table_id: u32) -> Self {
        Self {
            table_id,
            period_start_column: "sys_start".to_string(),
            period_end_column: "sys_end".to_string(),
        }
    }

    /// Creates with custom column names.
    pub fn with_columns(table_id: u32, start_col: String, end_col: String) -> Self {
        Self {
            table_id,
            period_start_column: start_col,
            period_end_column: end_col,
        }
    }

    /// Returns the columns required on the table.
    pub fn required_columns() -> Vec<(String, &'static str)> {
        vec![
            ("sys_start".to_string(), "TIMESTAMPTZ"),
            ("sys_end".to_string(), "TIMESTAMPTZ"),
        ]
    }

    /// Returns default values for INSERT: (sys_start, sys_end).
    #[inline]
    pub fn on_insert_defaults(now_micros: i64) -> (i64, i64) {
        (now_micros, MAX_TIMESTAMP)
    }

    /// Returns actions for UPDATE: expire old row, set new row timestamps.
    #[inline]
    pub fn on_update(now_micros: i64) -> SystemVersionedUpdateActions {
        SystemVersionedUpdateActions {
            old_sys_end: now_micros,
            new_sys_start: now_micros,
            new_sys_end: MAX_TIMESTAMP,
        }
    }

    /// Returns the sys_end value for DELETE.
    #[inline]
    pub fn on_delete(now_micros: i64) -> i64 {
        now_micros
    }
}

// ---------------------------------------------------------------------------
// Application-time table
// ---------------------------------------------------------------------------

/// Application-time table with user-managed valid time periods.
pub struct ApplicationTimeTable {
    pub table_id: u32,
    pub period_name: String,
    pub start_column: String,
    pub end_column: String,
}

/// Result of FOR PORTION OF splitting logic.
#[derive(Debug, Clone, PartialEq)]
pub struct ForPortionResult {
    /// Period before the portion (if existing_start < portion_start).
    pub before: Option<(i64, i64)>,
    /// The portion being updated.
    pub updated: (i64, i64),
    /// Period after the portion (if existing_end > portion_end).
    pub after: Option<(i64, i64)>,
}

impl ApplicationTimeTable {
    /// Creates a new application-time table configuration.
    pub fn new(table_id: u32, period_name: String, start_col: String, end_col: String) -> Self {
        Self {
            table_id,
            period_name,
            start_column: start_col,
            end_column: end_col,
        }
    }

    /// Validates that a period's start is before its end.
    pub fn validate_period(start: i64, end: i64) -> Result<()> {
        if start >= end {
            return Err(ZyronError::TemporalViolation(
                "period start must be before end".to_string(),
            ));
        }
        Ok(())
    }

    /// Computes the record split for FOR PORTION OF operations.
    ///
    /// Given an existing record with period [existing_start, existing_end)
    /// and a portion [portion_start, portion_end), returns up to 3 records:
    /// - before: [existing_start, portion_start) if existing_start < portion_start
    /// - updated: [max(existing_start, portion_start), min(existing_end, portion_end))
    /// - after: [portion_end, existing_end) if existing_end > portion_end
    pub fn split_for_portion(
        existing_start: i64,
        existing_end: i64,
        portion_start: i64,
        portion_end: i64,
    ) -> Result<ForPortionResult> {
        // No overlap check
        if existing_end <= portion_start || existing_start >= portion_end {
            return Err(ZyronError::TemporalViolation(
                "no overlap between existing period and portion".to_string(),
            ));
        }

        let before = if existing_start < portion_start {
            Some((existing_start, portion_start))
        } else {
            None
        };

        let updated_start = existing_start.max(portion_start);
        let updated_end = existing_end.min(portion_end);
        let updated = (updated_start, updated_end);

        let after = if existing_end > portion_end {
            Some((portion_end, existing_end))
        } else {
            None
        };

        Ok(ForPortionResult {
            before,
            updated,
            after,
        })
    }
}

// ---------------------------------------------------------------------------
// Bi-temporal table
// ---------------------------------------------------------------------------

/// Bi-temporal table combining system and application time.
pub struct BiTemporalTable {
    pub system: SystemVersionedTable,
    pub application: ApplicationTimeTable,
}

impl BiTemporalTable {
    /// Creates a new bi-temporal table.
    pub fn new(system: SystemVersionedTable, application: ApplicationTimeTable) -> Self {
        Self {
            system,
            application,
        }
    }
}

// ---------------------------------------------------------------------------
// Temporal query types
// ---------------------------------------------------------------------------

/// Temporal query filter specification.
#[derive(Debug, Clone, PartialEq)]
pub enum TemporalQuery {
    /// AS OF SYSTEM TIME <timestamp>
    AsOfSystemTime(i64),
    /// FOR SYSTEM_TIME BETWEEN <start> AND <end>
    BetweenSystemTime { start: i64, end: i64 },
    /// AS OF APPLICATION TIME <timestamp>
    AsOfApplicationTime(i64),
    /// FOR APPLICATION_TIME BETWEEN <start> AND <end>
    BetweenApplicationTime { start: i64, end: i64 },
    /// FOR PORTION OF <period> FROM <start> TO <end>
    ForPortionOf {
        period: String,
        start: i64,
        end: i64,
    },
}

impl TemporalQuery {
    /// Returns the column names to filter on based on the query type and config.
    pub fn to_filter_columns<'a>(&self, config: &'a TemporalConfig) -> (&'a str, &'a str) {
        match self {
            Self::AsOfSystemTime(_) | Self::BetweenSystemTime { .. } => {
                (&config.sys_start_column, &config.sys_end_column)
            }
            Self::AsOfApplicationTime(_) | Self::BetweenApplicationTime { .. } => {
                let start = config.app_start_column.as_deref().unwrap_or("app_start");
                let end = config.app_end_column.as_deref().unwrap_or("app_end");
                (start, end)
            }
            Self::ForPortionOf { .. } => {
                let start = config.app_start_column.as_deref().unwrap_or("app_start");
                let end = config.app_end_column.as_deref().unwrap_or("app_end");
                (start, end)
            }
        }
    }

    /// Returns the filter bounds (range_start, range_end).
    ///
    /// For AS OF queries: returns (point, point + 1) representing the
    /// instant at that timestamp.
    /// For BETWEEN queries: returns (start, end) inclusive range.
    pub fn to_filter_bounds(&self) -> (i64, i64) {
        match self {
            Self::AsOfSystemTime(ts) | Self::AsOfApplicationTime(ts) => (*ts, *ts),
            Self::BetweenSystemTime { start, end }
            | Self::BetweenApplicationTime { start, end } => (*start, *end),
            Self::ForPortionOf { start, end, .. } => (*start, *end),
        }
    }

    /// Returns true if a row with the given period is visible for this query.
    ///
    /// For AS OF: start_col <= point AND end_col > point
    /// For BETWEEN: start_col < range_end AND end_col > range_start
    pub fn is_row_visible(&self, row_start: i64, row_end: i64) -> bool {
        match self {
            Self::AsOfSystemTime(ts) | Self::AsOfApplicationTime(ts) => {
                row_start <= *ts && row_end > *ts
            }
            Self::BetweenSystemTime { start, end }
            | Self::BetweenApplicationTime { start, end }
            | Self::ForPortionOf { start, end, .. } => row_start < *end && row_end > *start,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_max_timestamp() {
        // 9999-12-31 23:59:59 UTC in microseconds
        assert!(MAX_TIMESTAMP > 0);
        assert_eq!(MAX_TIMESTAMP, 253_402_300_799_000_000);
    }

    #[test]
    fn test_system_versioned_insert_defaults() {
        let (start, end) = SystemVersionedTable::on_insert_defaults(1000);
        assert_eq!(start, 1000);
        assert_eq!(end, MAX_TIMESTAMP);
    }

    #[test]
    fn test_system_versioned_update() {
        let actions = SystemVersionedTable::on_update(5000);
        assert_eq!(actions.old_sys_end, 5000);
        assert_eq!(actions.new_sys_start, 5000);
        assert_eq!(actions.new_sys_end, MAX_TIMESTAMP);
    }

    #[test]
    fn test_system_versioned_delete() {
        assert_eq!(SystemVersionedTable::on_delete(9000), 9000);
    }

    #[test]
    fn test_validate_period() {
        assert!(ApplicationTimeTable::validate_period(100, 200).is_ok());
        assert!(ApplicationTimeTable::validate_period(100, 100).is_err());
        assert!(ApplicationTimeTable::validate_period(200, 100).is_err());
    }

    #[test]
    fn test_for_portion_full_containment() {
        // Existing [100, 500), portion [200, 400)
        let result = ApplicationTimeTable::split_for_portion(100, 500, 200, 400).expect("split");
        assert_eq!(result.before, Some((100, 200)));
        assert_eq!(result.updated, (200, 400));
        assert_eq!(result.after, Some((400, 500)));
    }

    #[test]
    fn test_for_portion_left_overlap() {
        // Existing [200, 500), portion [100, 300)
        let result = ApplicationTimeTable::split_for_portion(200, 500, 100, 300).expect("split");
        assert_eq!(result.before, None);
        assert_eq!(result.updated, (200, 300));
        assert_eq!(result.after, Some((300, 500)));
    }

    #[test]
    fn test_for_portion_right_overlap() {
        // Existing [100, 300), portion [200, 500)
        let result = ApplicationTimeTable::split_for_portion(100, 300, 200, 500).expect("split");
        assert_eq!(result.before, Some((100, 200)));
        assert_eq!(result.updated, (200, 300));
        assert_eq!(result.after, None);
    }

    #[test]
    fn test_for_portion_exact_match() {
        // Existing [100, 300), portion [100, 300)
        let result = ApplicationTimeTable::split_for_portion(100, 300, 100, 300).expect("split");
        assert_eq!(result.before, None);
        assert_eq!(result.updated, (100, 300));
        assert_eq!(result.after, None);
    }

    #[test]
    fn test_for_portion_no_overlap() {
        // Existing [100, 200), portion [300, 400)
        assert!(ApplicationTimeTable::split_for_portion(100, 200, 300, 400).is_err());
    }

    #[test]
    fn test_temporal_query_as_of_visibility() {
        let q = TemporalQuery::AsOfSystemTime(150);

        // Row [100, 200) is visible at 150
        assert!(q.is_row_visible(100, 200));
        // Row [100, 150) is not visible at 150 (end is exclusive)
        assert!(!q.is_row_visible(100, 150));
        // Row [200, 300) is not visible at 150
        assert!(!q.is_row_visible(200, 300));
        // Row [150, 300) is visible at 150
        assert!(q.is_row_visible(150, 300));
    }

    #[test]
    fn test_temporal_query_between_visibility() {
        let q = TemporalQuery::BetweenSystemTime {
            start: 100,
            end: 300,
        };

        // Row [50, 150) overlaps [100, 300)
        assert!(q.is_row_visible(50, 150));
        // Row [200, 400) overlaps [100, 300)
        assert!(q.is_row_visible(200, 400));
        // Row [300, 400) does not overlap (start >= end of range)
        assert!(!q.is_row_visible(300, 400));
        // Row [50, 100) does not overlap (end <= start of range)
        assert!(!q.is_row_visible(50, 100));
    }

    #[test]
    fn test_temporal_query_filter_columns() {
        let config = TemporalConfig {
            temporal_type: TemporalType::BiTemporal,
            sys_start_column: "sys_start".to_string(),
            sys_end_column: "sys_end".to_string(),
            app_period_name: Some("valid".to_string()),
            app_start_column: Some("valid_from".to_string()),
            app_end_column: Some("valid_to".to_string()),
        };

        let q = TemporalQuery::AsOfSystemTime(100);
        let (s, e) = q.to_filter_columns(&config);
        assert_eq!(s, "sys_start");
        assert_eq!(e, "sys_end");

        let q = TemporalQuery::AsOfApplicationTime(100);
        let (s, e) = q.to_filter_columns(&config);
        assert_eq!(s, "valid_from");
        assert_eq!(e, "valid_to");
    }

    #[test]
    fn test_temporal_query_filter_bounds() {
        let q = TemporalQuery::AsOfSystemTime(1000);
        assert_eq!(q.to_filter_bounds(), (1000, 1000));

        let q = TemporalQuery::BetweenSystemTime {
            start: 100,
            end: 500,
        };
        assert_eq!(q.to_filter_bounds(), (100, 500));
    }

    #[test]
    fn test_system_versioned_required_columns() {
        let cols = SystemVersionedTable::required_columns();
        assert_eq!(cols.len(), 2);
        assert_eq!(cols[0].0, "sys_start");
        assert_eq!(cols[1].0, "sys_end");
    }
}
