[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+avx2,+bmi2"]

[alias]
zyron = "run --release --bin zyron-server --"
cli = "run --release --bin zyron-cli --"
bench-search = "test -p zyron-search --test search_bench --release -- --nocapture --test-threads=1"
