[package]
name = "zyron-analytics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
zyron-common = { path = "../zyron-common" }
zyron-search = { path = "../zyron-search" }
parking_lot.workspace = true
serde.workspace = true

[dev-dependencies]
zyron-bench-harness = { path = "../zyron-bench-harness" }
