[package]
name = "zyron-planner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
zyron-common = { path = "../zyron-common" }
zyron-parser = { path = "../zyron-parser" }
zyron-catalog = { path = "../zyron-catalog" }
zyron-lake = { path = "../zyron-lake" }
zyron-types = { path = "../zyron-types" }
zyron-analytics = { path = "../zyron-analytics" }
zyron-lifecycle = { path = "../zyron-lifecycle" }
tokio.workspace = true
sha2.workspace = true

[dev-dependencies]
zyron-buffer = { path = "../zyron-buffer" }
zyron-storage = { path = "../zyron-storage" }
zyron-wal = { path = "../zyron-wal" }
tempfile = "3.27.0"
zyron-bench-harness = { path = "../zyron-bench-harness" }
